import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const srcDir = join(import.meta.dir, "..", "src");

const SOURCE_FILES = [
	"routes/simple-form.tsx",
	"routes/nested-form.tsx",
	"routes/array-form.tsx",
	"routes/custom-field-types.tsx",
	"routes/custom-field-component.tsx",
	"components/form-wrapper.tsx",
	"lib/form.tsx",
] as const;

const entries = SOURCE_FILES.map((rel) => {
	const abs = join(srcDir, rel);
	const content = readFileSync(abs, "utf-8");
	const parts = rel.split("/");
	const name = parts[parts.length - 1] ?? rel;
	return [rel, { content, name }] as const;
});

const lines = [
	"// This file is auto-generated by scripts/generate-sources.ts",
	"// Do not edit manually — run `bun run generate:sources` to regenerate.",
	"",
	"export interface SourceFile {",
	"  name: string;",
	"  content: string;",
	"}",
	"",
	"export const exampleSources: Record<string, SourceFile> = {",
];

for (const [rel, { name, content }] of entries) {
	lines.push(`  ${JSON.stringify(rel)}: {`);
	lines.push(`    name: ${JSON.stringify(name)},`);
	lines.push(`    content: ${JSON.stringify(content)},`);
	lines.push("  },");
}

lines.push("};");
lines.push("");

const outPath = join(srcDir, "lib", "example-sources.gen.ts");
writeFileSync(outPath, lines.join("\n"));
console.log(`Generated ${outPath}`);
